sudo: false
language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools
    # The SDK version used to compile your project
    - android-24
    - tools
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-24.0.1


    # Support library
    - extra-android-support
    - extra-android-m2repository

script:
  - adb devices
  - ./gradlew assembleDebug
  - ./gradlew :testDebug

before_install:
  - chmod +x gradlew