language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-24  ANDROID_ABI=armeabi-v7a
android:
  components:
    - build-tools-24.0.1
script:
  - ./gradlew build
before_install:
 - chmod +x gradlew


