language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-24.0.1
    - platform-tools
    - android-24
    - extra-android-m2repository
script:
  - ./gradlew build
before_install:
 - chmod +x gradlew


